service: ascension-server

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
#  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs14.x
  stage: production
  region: us-east-1

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: hello
          method: get